# Generated by Django 6.0.5 on 2026-05-16 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='semester',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
